### ISSUE TITLE
Crashing.

### ISSUE THREAD

**Issue by EzelsKodDiyar** [hypixeI/ape-installer#1]
Crashing When i inject

**Comment by Raacccoon** [comment]
skill issue

**Comment by hypixeI** [comment]
Hi! Could you please inform which version of Ape was used?
Along with which version of Minecraft and what mods you had installed?

**Comment by hypixeI** [comment]
didnt respond, please join the discord for support.
however, here is a fix:
this only works on forge, use forge, otherwise it crashes
